version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "rewards-migrations-loy-member-topic:1:1,
      rewards-migrations-contacts-topic:1:1,
      rewards-migrations-addresses-by-row-id-topic:1:1,
      rewards-migrations-contacts-x-topic:1:1,
      rewards-migrations-loy-card-topic:1:1,
      rewards-migrations-loy-member-topic:1:1,
      rewards-migrations-loy-member-tier-topic:1:1,
      rewards-migrations-loy-member-x-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
